vms:
  hosts:
    vm0:
      ansible_host: ""
      ansible_user: "challenge"
      ansible_ssh_private_key_file: "../challenge"
    vm1:
      ansible_host: ""
      ansible_user: "challenge"
      ansible_ssh_private_key_file: "../challenge"
    vm2:
      ansible_host: ""
      ansible_user: "challenge"
      ansible_ssh_private_key_file: "../challenge"
